### ISSUE TITLE
Fix mirrors cert

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#140]
Cert expired; let's encrypt is probably not on a Cron job

**Comment by axk4545** [comment]
Sorry guys.

On Sep 14, 2018 4:37 PM, "Christian Martin" <notifications@github.com>
wrote:

Cert expired; let's encrypt is probably not on a Cron job

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RITlug/TigerOS/issues/140>, or mute the thread

**Comment by Tjzabel** [comment]
@ct-martin this should be an immediate next priority. Packages cannot safely pull from the TigerOS mirror with a missing cert.

**Comment by ct-martin** [comment]
The command in the cron job was for a different version of certbot, I have renewed the cert and updated the crontab

(cc @Tjzabel )
