### ISSUE TITLE
Packages to include in distro

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#4]
What packages would be useful to the RIT community (students, new Linux users, professors,etc) and should be included in our distribution?
below are some suggestions I have. Currently I am envisioning that the base image will include very few packages and we will specify what to add.
- Base: wget, libreoffice, thunderbird, gimp, inkscape, rhythmbox, htop, vim, zsh, nano, wine, hexchat, lynx, evince, firefox, chrome, grscreenshot, vbox, openjdk
- IST/WMC: mysql/mariadb, mongodb, apache, nodejs, php, jGrasp, filezilla, subversion
- NSSA/CIT: wireshark, python, git, jGrasp
- CS: Intellij, Pycharm, racket, prolog, logisim jar, my wget script to fetch assignments https://github.com/axk4545/linux-stuff/blob/master/fetch, JFLAP(http://www.jflap.org/jflaptmp/may15-2011/withoutSource/JFLAP.jar) see license http://www.cs.duke.edu/csed/jflap/jflaptmp/aug28-09/license.html for conditions
- SE: java, ruby, Alloy (http://alloy.mit.edu/alloy/download.html), Spin (http://spinroot.com/spin/Man/README.html, sqlite3, eclipse 

- [x] Base packages added
- [x] IST/WMC
- [x] NSSA/CIT
- [x] CS
- [x] SE

**Comment by thenaterhood** [comment]
gscreenshot is a nice, lightweight screenshot tool. https://github.com/thenaterhood/gscreenshot. Not currently packaged for RPM, but should be easy enough since it's a python application.

**Comment by ReginaTL** [comment]
If you wanted a full graphic design/artist suite on the system you may want to add Krita, it's mostly for digital painting but you can do other cool stuff on there too. If it isn't in the default it shoudl be suggested in the wiki somewhere. We may want to create either install instructions/scripts for different common tools in classes like installing mysql etc. or include them by default.

**Comment by axk4545** [comment]
Good idea. Will talk to IST sys admins about what software their students use. @RITlug/rit-linux-team could someone in SE and someone in CS get a list of essential things for students in their departments? any other recommendations are welcome too of course. CSEC would do most things in a Kali live environment AFAIK.

**Comment by ReginaTL** [comment]
In that case we might want to have VirtualBox available either as default or in the CSEC package as an alternative to VMWare. I can make a list of some of the intro to CS stuff as I took CS I and II if we can't find anyone.

**Comment by axk4545** [comment]
IST: mysql/maria, mongo, php, apache, oracle java, nodejs
NSSA: wireshark, python, git, jgrasp

**Comment by Josh1147582** [comment]
For CS:
Maybe an IDE for Java and Python development? Because there's a lot of that, in CS and not in CS. Eclipse was the standard in CS for AP students a few semesters ago. IntelliJ's IDEA and PyCharm are much more popular among students, I don't know what they're licensing would allow us to do.
Mechanics of Programming works with C, so gcc and make would be good.
Programming Language Concepts uses racket, and I think prolog, but we haven't gotten to prolog in class yet, so I can't provide much information.

Also, for many majors, tools for LaTeX documents would be nice as well. It's useful in some CS courses, and useful when building a resume.

**Comment by ReginaTL** [comment]
For Intellij and PyCharm there should be at least something in the documentation that explains .tar.gz files and what to do with them. Maybe we can create a script that installs the tar.gz? I don't remember if I had to do something extra to get it as a shortcut in my menu because we can include that too. 

Personally I feel git should be default.

Web and Mobile: I feel there should be firefox developer edition, as it has a way to reduce the screen size to whatever resolution you want and saves pre-sets, it's pretty awesome for web development. Also SVN is used in their one Software Engineering class specific to WMC.

SE: I know uses Ruby and C for personal software engineering. They also need Java to run Robocode in one of their Freshman classes.

**Comment by axk4545** [comment]
@RITlug/rit-linux-team please look at the first entry in this issue and vote with a thumb reaction. If we all approve I will add the base packages to the kickstart and begin building. Please also add your names and roles to the README. Also feel free to self assign any of the issues listed under projects to work on. When do in the work please for the repo and pull request into the devel branch.

**Comment by axk4545** [comment]
@RITlug/rit-linux-team If there are no objects I will be adding the base packages to the kickstart.

**Comment by linux-modder** [comment]
Trying to help with the postinstall for you folks and have a few questions:

SE: 
sqlite3 needs what files exactly?  sqlite3 has like 20 sub-packages on Fedora
will sqlcipher be needed for entry obfuscation/security?

**Comment by thenaterhood** [comment]
Vanilla sqlite3 should be enough as far as I'm aware.

**Comment by axk4545** [comment]
Scripts created except for jGrasp due to license. Closing.
