### ISSUE TITLE
Reevaluate desktop environment

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#41]
@axk4545

**Comment by axk4545** [comment]
@ctm2142 ISO size is also something to consider. GNOME is pretty big

**Comment by Josh1147582** [comment]
To consider as well: how much emphasis on DE choice are we going to put in the docs?

If we have several sections/DEs, descriptions of them, install guides, etc., then that might change how high of a priority the out of the box DE is.

**Comment by jflory7** [comment]
> @ctm2142 ISO size is also something to consider. GNOME is pretty big

It's also a comparable question, is bandwidth and our image size a concern for our target audience, i.e. RIT students (on the RIT network) or RIT lab computers? I'm not sure if the image size is too much of a concern for our use case. While it is generally important, I don't know if it's critical for the context of RIT's gigabit network.

**Comment by axk4545** [comment]
@jflory7 On a technical side, the larger the ISO the more space we need on the mirror and the longer it will take to build. There are also limits to the capacity of the physical media depending on what it is. I am trying to keep it flexible.

**Comment by Tjzabel** [comment]
@axk4545 I understand we are trying to keep the size of the ISO as small as possible, but does changing a DE from Cinnamon to Gnome drastically increase the size of the ISO so much as to rethink doing so?

**Comment by axk4545** [comment]
@axk4545 Maybe. This will all need to be evaluated as part of the switch. first steps are probably do we want ot switch and if so to what. Then deal with implications a little more.

**Comment by axk4545** [comment]
If we do go gnome, I know there was some talk of dash to dock. I propose using [dash to panel](https://github.com/jderose9/dash-to-panel) in its place.

**Comment by Tjzabel** [comment]
@axk4545 that sounds like a good idea. I'll look into it on my own laptop (I'm running fedora 26 gnome) as well and see how it is.

**Comment by Josh1147582** [comment]
Also kinda related (not sure if it deserves its own issue):

When running a live USB on my laptop (devel-20170910), there's currently no way to connect to the RIT WPA2 enterprise network with Cinnamon's network manager. Selecting RIT from the task icon bring up Cinnamon's network settings program. Selecting RIT from there does nothing.

As of now, to connect to RIT, I must remove Cinnamon's network applet from the taskbar, then launch nm-applet.

It might be possible to [https://forums.linuxmint.com/viewtopic.php?t=97426](configure Cinnamon to use nm-applet), but I'm not sure how to include such changes in the build.

**Comment by linux-modder** [comment]
@Josh1147582,

ls /etc/sysconfig/network-scripts/  shows anything for ifcfg-RIT or similar?  Also, keep in mind even if it did as the wpa or even peap (eduroam) networks on ANY university require a u/n  ( in some cases an additional CERT/PKI factor) which can not be hardcoded. Try adding info into the ../network-scripts/ifcfg-RIT   file (info = {u/n} )

**Comment by Josh1147582** [comment]
@linux-modder

/etc/sysconfig/network-scripts/ was empty. I didn't try adding/configuring a file manually, since I didn't think we would expect users to do that, and hardcoding a solution would be impossible. Also, using nm-applet to select, configure, and connect to the network works just fine. But I might try spinning it up again and making my own config file, to see if I can get Cinnamon's network manager applet to work with it. 

`journalctl -u NetworkManager` didn't log anything when I tried to connect with Cinnamon's network manager applet, which I found strange. That almost sounds like a missing dependency.

**Comment by Josh1147582** [comment]
Update to my Cinnamon wifi issue above.

I get the same issue on a live USB of [https://spins.fedoraproject.org/cinnamon/](Fedora's Cinnamon Spin). So it seems it's an issue with Cinnamon, or Cinnamon on Fedora. I'm interested to see if anyone but me has this issue as well: if it's common, we may want to consider a DE switch.

**Comment by linux-modder** [comment]
it's a part of cinnamon's NetworkManager-wifi  and network-manager-applet not talking natively.

**Comment by jflory7** [comment]
_Discussed in 2017-10-06 TigerOS meeting._

## Current status

* **WiFi**: Added packages needed to get WiFi working out of the box for WPA2 Enterprise, needs testing

## Points of consideration for changing

* **To GNOME**:
    * Working directly with default desktop environment from upstream
    * With dash-to-dock, create a friendly, familiar, and modern user experience
    * Feels "newer" than Cinnamon
* **Staying on Cinnamon**:
    * Needs working WiFi
    * Needs customizations / UI tweaks to feel more modern

## Where we are now

From our discussion, we decided to first work on getting working drivers for the WPA2 Enterprise network. @axk4545 will create new kickstarts and @ct-martin will build the ISOs. After, we'll do some testing to verify the fixes worked.

**Comment by jflory7** [comment]
_Discussed in 2017-10-13 TigerOS meeting._

## Summary

The four present members (of seven total) in the meeting voted to **switch the TigerOS desktop environment to GNOME3 with dash-to-dock**.

## Explanation

If you look through some of the other issues, more research and testing was done on the GNOME / Cinnamon DEs. Cinnamon is still unable to authenticate automatically with RIT's 802.1x network, among other smaller issues. Since we agreed last meeting that the 802.1x issue was a "deal breaker", we moved forward with the decision to switch.

Since this issue is more conceptual, I'm closing it since a decision was reached. Other tickets will detail the work that needs to be done to make the switch to GNOME3.
