### ISSUE TITLE
how do we want to do provisioning/setup?

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#5]
We have a few options:
1. Fedora custom iso generated with kickstart(current state)
    * Allows custom iso so any configs and changes can be included in image, minimal work for user. essentially a remaster
2. Ubuntu minimal iso and kickstart based install
    * slightly less flexible. cannot embed customizations in image, maybe limited as kickstart is the RedHat autoinstall method
3. Ubuntu minimal iso and preseed install
    * slightly less flexible. cannot embed customizations in image, minimal work for user but would require learning how to make a preseed on our end.
4. Ubuntu minimal iso and ansible playbook to customize system
    * easiest approach however all of the custom stuff would be done post install, more work for user. 
There are of course a few other options. Let me know what you think.

**Comment by abkahrs** [comment]
Originally written by @jflory7 
Hi! Wanting to weigh in on this…

# Choosing a distro

I was unaware of the technical differences between creating a RIT Linux Remix, but it seems that Fedora has the easier tooling to provision and create a distribution we can easily package and offer to users without putting too much work onto them. However, the case I wanted to make for Fedora is that I want to help communicate and share some of the work that might go into this project across the Fedora and wider open source community. If we choose Fedora, it will be easier for me to promote the RIT Remix across the Fedora community and in even in places like the Fedora Magazine. However, choosing another distribution would make it more difficult for me to do something like this mostly because I don't have the same connections and familiarity with other communities as I do with Fedora.

I give a :+1: for the Fedora option for the purpose of having some really cool opportunities to share and promote any work on an RIT Remix distro with a wider community and hopefully make it more widely visible within and outside of RIT.

# What really matters

However, with the above point, I recognize there are some **key points that need to be considered with whatever we choose**. Ultimately, if we are going to try setting up and re-creating the go-to RIT Linux Remix, these points should be considered:

1. What provides the **easiest experience for the user to install and run the RIT Remix**? What simplifies the experience for a student who may not have ever tried using Linux before?
2. What is the **easiest method to package and prepare this as the maintainers**? We should consider the tools and resources available that simplify how we build and prepare this so that we can more easily introduce new contributors in the event the project lead loses interest (this isn't to poke at a specific person, but rather more focused on long-term planning for keeping this as a resource for students one year, five years, or even ten years down the road – best to plan for it now while we have a chance to think about this!).
3. What do we want to offer in this Remix **specific to RIT students**? Before getting caught up in _what_ we use, let's think about _why_ first: what do we want to include in our Remix, and what option best enables us to include those things?

I may think of more things, but I highly encourage us to answer these questions (especially num. 3!) first before settling on an option.

**Comment by abkahrs** [comment]
@serubin mentioning you here so you are in the loop

**Comment by abkahrs** [comment]
also a possibility to use the approach of a shell script or a deb package to do all the tasks

**Comment by abkahrs** [comment]
Current plan:
- Fedora spin using kickstart
- see https://etherpad.gnome.org/p/rit-remix-discussion for customizations
- branding considerations: https://fedoraproject.org/wiki/Remix#Can_a_Fedora_Remix_have_a_different_branding.3F

**Comment by abkahrs** [comment]
@jflory7 @serubin I think we are pretty settled on this. Ok to close?
