### ISSUE TITLE
Fix dark backgrounds

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#75]
Off-center issue still exists. Additionally, you need the font installed on your system to render it correctly, could we have 1080p renders?

cc @axk4545 @ReginaTL

**Comment by jflory7** [comment]
_Discussed in our [weekly meeting](https://github.com/RITlug/TigerOS/wiki/Next-meeting-agenda)._

## Need updated rendered dark backgrounds

The dark background wallpapers are slightly off-center and need a minor tweak to center them. Other team members had issues getting the fonts or they would update it themselves (since we only have vector images now).

@ReginaTL, could you export new, rendered screenshots that are centered, and then submit a new PR with…

* New rendered, exported graphics
* Updated vector images

We can also discuss this at a general meeting too.

**Comment by Tjzabel** [comment]
Most of these issues seem to have been resolved at this point. Closing this issue until further notice.
